services:
  nginx:
    image: nginx:1.25-alpine
    container_name: wingman_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - ./media:/app/media 
    depends_on:
      - web

  web:
    build: .
    container_name: wingman_web
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - RUNNING_IN_DOCKER=true
    volumes:
      - static_volume:/app/staticfiles
      - ./media:/app/media 
      - ./logs:/app/logs
    depends_on:
      - redis

  celery:
    build: .
    container_name: wingman_celery
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - RUNNING_IN_DOCKER=true
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    depends_on:
      - redis
    command: celery -A wingman worker --loglevel=info

  celery-beat:
    build: .
    container_name: wingman_beat
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - RUNNING_IN_DOCKER=true
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    depends_on:
      - redis
    command: celery -A wingman beat --loglevel=info

  redis:
    image: redis:7-alpine
    container_name: wingman_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  static_volume:
  redis_data: